### ISSUE TITLE
Playing an uploaded file

### ISSUE THREAD

**Issue by JoePShoulak** [jazz-soft/react-midi-player#3]
Hello!

I'm working on a web app that handles midi files and I'd like for my users to be able to play midi files that they've dragged-and-dropped into the web browser. 

I'm using a package called [@dropzone-ui/react](https://www.npmjs.com/package/@dropzone-ui/react) which gives me an object (let's call it `myFile`) where `myFile.file` is the midi file data. 

Your package takes either the actual midi data or a file path, but this file object I'm handling didn't like being passed in as the data option. I was wondering if you had any suggestions for how I might still be able to play it?

**Comment by jazz-soft** [comment]
Hi! Thanks for asking!
What is the format of the data you get from @dropzone-ui/react ?

**Comment by JoePShoulak** [comment]
Thanks for the quick response! I don't have much experience in file handling. I get what I'm calling `myFile` from dropzone, and it's basically just an object they use for sugar on top inside the rendering of their component. The file itself is the `myFile.file` property. In my app, that's what I'm sending in a post request to my express backend where I'm doing things to it using a python script and sending some text back. I send the file to express by doing the following, maybe that will be enough to suss out what type it is:


(in the following code, assume `file = myFile.file` to relate to how I was talking about it earlier)
```javascript
  const formData = new FormData();
  formData.append("file", file);

  const fetchOptions = {
    method: "POST",
    body: formData,
  };

  return fetch("/api/process", fetchOptions).then(res => res.json());
```

**Comment by jazz-soft** [comment]
Perhaps you should check with the @dropzone_ui support how to get the binary data from the uploaded file.
Then I'll be able to help you with the MIDI player.

**Comment by JoePShoulak** [comment]
Figured it out and found a new favorite helper function along the way!

If you've got the file loaded up already as a variable and you want to pass it to something expecting a path without saving it just for that purpose, you can use this:

```javascript
const virtualLink = f => URL.createObjectURL(new Blob([f], { type: f.type }));
```

Then I could just do this:
```javascript
<MidiPlayer src={virtualLink(midiFile)} />
```
